language: r
cache: packages
before_install:
  - sudo rm -vf /etc/apt/sources.list.d/*riak*
  - sudo apt-get update
  - cd dataCompareR
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
